apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "demo.fullname" . }}-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
