apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "demo.fullname" . }}-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/influxdb"