apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}-db
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "demo.dbSelectorLabels" . | nindent 4 }}
